import type { NicheConfig } from '../types';

// Конфиг ниш: поля карточки CRM, ROI-параметры и скриптованный сценарий для симулятора.
// Скрипт = ровно та последовательность реплик и tool-вызовов, что прислал бы агент Dasha.

const dental: NicheConfig = {
  id: 'dental',
  label: 'Стоматология',
  emoji: '🦷',
  agentName: 'Анна, администратор клиники',
  disclaimer: '🔬 Демо-режим: представлен ограниченный набор услуг, чтобы показать принцип работы. В реальной клинике бот подключается к полному прайсу через векторную базу данных и мгновенно находит нужную позицию среди 1 000+ услуг.',
  fields: [
    { key: 'name', label: 'Имя' },
    { key: 'phone', label: 'Телефон' },
    { key: 'service', label: 'Услуга' },
    { key: 'master', label: 'Врач' },
    { key: 'date', label: 'Дата и время' },
  ],
  roi: {
    aiCostPerCall: 4,
    humanCostPerCall: 55,
    missedCallValue: 4500, // несостоявшийся приём
    defaultCallsPerDay: 40,
    defaultManagerSalary: 60000,
  },
  crmView: 'calendar',
  script: [
    { at: 600, say: { from: 'agent', text: 'Стоматология «Денталюкс», меня зовут Анна. Чем могу помочь?' } },
    { at: 2200, say: { from: 'user', text: 'Здравствуйте, хочу записаться на чистку зубов.' } },
    { at: 3200, tool: { name: 'update_card', args: { field: 'service', value: 'Профгигиена (чистка)' } } },
    { at: 3800, say: { from: 'agent', text: 'Конечно. Подскажите, как вас зовут?' } },
    { at: 5200, say: { from: 'user', text: 'Игорь.' } },
    { at: 5600, tool: { name: 'update_card', args: { field: 'name', value: 'Игорь' } } },
    { at: 6400, say: { from: 'agent', text: 'Игорь, на какую дату удобно?' } },
    { at: 7800, say: { from: 'user', text: 'Можно в эту субботу.' } },
    { at: 8200, say: { from: 'agent', text: 'Минутку, проверяю расписание…' } },
    { at: 9800, tool: { name: 'update_card', args: { field: 'date', value: 'Сб, 14:30' } } },
    { at: 10200, tool: { name: 'update_card', args: { field: 'master', value: 'Гигиенист Петрова' } } },
    { at: 10600, say: { from: 'agent', text: 'Есть суббота в 14:30 у гигиениста Петровой. Записываю?' } },
    { at: 12000, say: { from: 'user', text: 'Да, давайте.' } },
    { at: 12300, tool: { name: 'book_appointment', args: { day: 'суббота', time: '14:30', service: 'Профгигиена (чистка)', client: 'Игорь', master: 'Гигиенист Петрова' } } },
    { at: 12600, tool: { name: 'lead_score', args: { score: 85, sentiment: 'позитивный' } } },
    { at: 13200, tool: { name: 'show_sms', args: { text: 'Вы записаны: Сб 14:30. Подтвердите визит:', link: 'денталюкс.рф/visit/8421' } } },
    { at: 14200, tool: { name: 'set_summary', args: { text: 'Игорь записан на профгигиену в субботу 14:30 к гигиенисту Петровой. Отправлено SMS с подтверждением.' } } },
    { at: 15200, say: { from: 'agent', text: 'Готово! Отправила вам SMS со ссылкой на подтверждение. Ждём вас в субботу.' } },
    { at: 16500, tool: { name: 'request_callback', args: { delaySeconds: 10, reason: 'Напоминание о визите за день' } } },
  ],
};

const auto: NicheConfig = {
  id: 'auto',
  label: 'Автосервис',
  emoji: '🔧',
  agentName: 'Сергей, мастер-приёмщик',
  fields: [
    { key: 'name', label: 'Имя' },
    { key: 'phone', label: 'Телефон' },
    { key: 'car', label: 'Автомобиль' },
    { key: 'service', label: 'Работа' },
    { key: 'master', label: 'Механик' },
    { key: 'date', label: 'Запись' },
  ],
  roi: {
    aiCostPerCall: 4,
    humanCostPerCall: 50,
    missedCallValue: 6000,
    defaultCallsPerDay: 35,
    defaultManagerSalary: 65000,
  },
  crmView: 'calendar',
  script: [
    { at: 600, say: { from: 'agent', text: 'Автосервис «ТочкаОпоры», Сергей. Слушаю вас.' } },
    { at: 2200, say: { from: 'user', text: 'Нужно записаться на замену масла, машина Киа Рио.' } },
    { at: 3000, tool: { name: 'update_card', args: { field: 'car', value: 'Kia Rio' } } },
    { at: 3500, tool: { name: 'update_card', args: { field: 'service', value: 'Замена масла + фильтр' } } },
    { at: 4200, say: { from: 'agent', text: 'Принял. Как к вам обращаться?' } },
    { at: 5400, say: { from: 'user', text: 'Дмитрий.' } },
    { at: 5800, tool: { name: 'update_card', args: { field: 'name', value: 'Дмитрий' } } },
    { at: 6600, say: { from: 'agent', text: 'Секунду, смотрю свободные окна…' } },
    { at: 8000, tool: { name: 'update_card', args: { field: 'master', value: 'Механик Алексей' } } },
    { at: 8400, tool: { name: 'update_card', args: { field: 'date', value: 'Завтра, 11:00' } } },
    { at: 8900, say: { from: 'agent', text: 'Есть завтра в 11:00 у механика Алексея. Подходит?' } },
    { at: 10200, say: { from: 'user', text: 'Да, отлично.' } },
    { at: 10500, tool: { name: 'book_appointment', args: { day: 'завтра', time: '11:00', service: 'Замена масла + фильтр', client: 'Дмитрий', master: 'Механик Алексей' } } },
    { at: 11000, say: { from: 'agent', text: 'Записал. Продиктуйте номер телефона, отправлю SMS с адресом.' } },
    { at: 12200, say: { from: 'user', text: '89031234567' } },
    { at: 12600, tool: { name: 'update_card', args: { field: 'phone', value: '+7 903 123-45-67' } } },
    { at: 13000, tool: { name: 'lead_score', args: { score: 78, sentiment: 'позитивный' } } },
    { at: 13600, tool: { name: 'show_sms', args: { text: 'Запись на замену масла завтра 11:00. Адрес и детали:', link: 'точкаопоры.рф/z/3391' } } },
    { at: 14600, tool: { name: 'set_summary', args: { text: 'Дмитрий, Kia Rio — замена масла и фильтра, запись на завтра 11:00 (механик Алексей). Отправлено SMS с адресом.' } } },
    { at: 15600, say: { from: 'agent', text: 'SMS отправил. До завтра, Дмитрий!' } },
  ],
};

const meat: NicheConfig = {
  id: 'meat',
  label: 'Meat Foods (мясо опт)',
  emoji: '🥩',
  agentName: 'Ольга, менеджер Meat Foods',
  fields: [
    { key: 'company', label: 'Компания' },
    { key: 'name', label: 'Контакт' },
    { key: 'phone', label: 'Телефон' },
    { key: 'address', label: 'Адрес доставки' },
  ],
  roi: {
    aiCostPerCall: 5,
    humanCostPerCall: 70,
    missedCallValue: 25000, // упущенная оптовая заявка
    defaultCallsPerDay: 25,
    defaultManagerSalary: 80000,
  },
  crmView: 'order',
  script: [
    { at: 600, say: { from: 'agent', text: 'Meat Foods, здравствуйте! Меня зовут Ольга. Помогу подобрать продукцию и оформить заказ. Что вас интересует?' } },
    { at: 2600, say: { from: 'user', text: 'Нужно филе грудки и заготовка для шаурмы из курицы.' } },
    { at: 3200, tool: { name: 'add_order_item', args: { name: 'Филе грудки (халяль)', price: 420, qty: 10, unit: 'кг' } } },
    { at: 3800, say: { from: 'agent', text: 'Записала. Сколько филе грудки и заготовки для шаурмы — в килограммах?' } },
    { at: 5400, say: { from: 'user', text: '10 кг филе и 15 кг заготовки.' } },
    { at: 6000, tool: { name: 'add_order_item', args: { name: 'Заготовка для шаурмы (курица)', price: 320, qty: 15, unit: 'кг' } } },
    { at: 6800, say: { from: 'agent', text: 'Итого 25 кг — по Москве доставка бесплатная. Куда везём?' } },
    { at: 8200, say: { from: 'user', text: 'Ресторан «Прайм», Москва, ул. Тверская 5.' } },
    { at: 8700, tool: { name: 'update_card', args: { field: 'company', value: 'Ресторан «Прайм»' } } },
    { at: 9100, tool: { name: 'update_card', args: { field: 'address', value: 'Москва, ул. Тверская 5' } } },
    { at: 9800, say: { from: 'agent', text: 'На какую дату и время оформляем доставку?' } },
    { at: 11200, say: { from: 'user', text: 'Завтра к 10 утра. Андрей, 8 900 111 22 33.' } },
    { at: 11700, tool: { name: 'update_card', args: { field: 'name', value: 'Андрей' } } },
    { at: 12100, tool: { name: 'update_card', args: { field: 'phone', value: '8 900 111 22 33' } } },
    { at: 12800, say: { from: 'agent', text: 'Секунду, оформляю заказ…' } },
    { at: 13600, tool: { name: 'place_order', args: { deliveryTime: 'завтра к 10:00' } } },
    { at: 14200, say: { from: 'agent', text: 'Итого 9 000 ₽, доставка бесплатно. Отправляю подтверждение в SMS.' } },
    { at: 14800, tool: { name: 'show_sms', args: { text: 'Заказ Meat Foods на 9 000 ₽, доставка завтра к 10:00:', link: 'meatfoods.ru/order/3471' } } },
    { at: 15600, tool: { name: 'lead_score', args: { score: 90, sentiment: 'горячий' } } },
    { at: 16400, tool: { name: 'set_summary', args: { text: 'Ресторан «Прайм» (Андрей): филе грудки 10 кг + заготовка для шаурмы (курица) 15 кг = 9 000 ₽. Доставка завтра к 10:00, Москва, Тверская 5. Отправлено SMS.' } } },
    { at: 17200, say: { from: 'agent', text: 'Заказ принят! Доставим завтра к 10:00. Спасибо, что выбрали Meat Foods.' } },
  ],
};

const salon: NicheConfig = {
  id: 'salon',
  label: 'Салон красоты',
  emoji: '💇',
  agentName: 'Карина, администратор',
  fields: [
    { key: 'name', label: 'Имя' },
    { key: 'phone', label: 'Телефон' },
    { key: 'service', label: 'Услуга' },
    { key: 'master', label: 'Мастер' },
    { key: 'date', label: 'Дата и время' },
  ],
  roi: {
    aiCostPerCall: 4,
    humanCostPerCall: 45,
    missedCallValue: 3000,
    defaultCallsPerDay: 50,
    defaultManagerSalary: 50000,
  },
  crmView: 'calendar',
  script: [
    { at: 600, say: { from: 'agent', text: 'Салон «Шарм», администратор Карина. Здравствуйте!' } },
    { at: 2200, say: { from: 'user', text: 'Хочу записаться на стрижку и окрашивание.' } },
    { at: 3000, tool: { name: 'update_card', args: { field: 'service', value: 'Стрижка + окрашивание' } } },
    { at: 3800, say: { from: 'agent', text: 'Прекрасно! Как вас зовут?' } },
    { at: 5000, say: { from: 'user', text: 'Марина.' } },
    { at: 5400, tool: { name: 'update_card', args: { field: 'name', value: 'Марина' } } },
    { at: 6200, say: { from: 'agent', text: 'Минутку, подбираю мастера и время…' } },
    { at: 8000, tool: { name: 'update_card', args: { field: 'master', value: 'Стилист Юлия' } } },
    { at: 8400, tool: { name: 'update_card', args: { field: 'date', value: 'Чт, 18:00' } } },
    { at: 8900, say: { from: 'agent', text: 'Есть четверг в 18:00 у стилиста Юлии. Записываю?' } },
    { at: 10200, say: { from: 'user', text: 'Да!' } },
    { at: 10500, tool: { name: 'book_appointment', args: { day: 'четверг', time: '18:00', service: 'Стрижка + окрашивание', client: 'Марина', master: 'Стилист Юлия' } } },
    { at: 10800, tool: { name: 'lead_score', args: { score: 80, sentiment: 'позитивный' } } },
    { at: 11400, tool: { name: 'show_sms', args: { text: 'Запись: Чт 18:00, стилист Юлия. Перенести/отменить:', link: 'шарм.рф/v/5563' } } },
    { at: 12400, tool: { name: 'set_summary', args: { text: 'Марина — стрижка и окрашивание, четверг 18:00, стилист Юлия. Отправлено SMS с записью.' } } },
    { at: 13400, say: { from: 'agent', text: 'Записала! Прислала SMS с деталями. Ждём вас в четверг.' } },
  ],
};

const food: NicheConfig = {
  id: 'food',
  label: 'Доставка еды',
  emoji: '🍕',
  agentName: 'Алексей, оператор доставки',
  fields: [
    { key: 'name', label: 'Имя' },
    { key: 'phone', label: 'Телефон' },
    { key: 'address', label: 'Адрес' },
    { key: 'payment', label: 'Оплата' },
  ],
  roi: {
    aiCostPerCall: 4,
    humanCostPerCall: 45,
    missedCallValue: 1200, // упущенный заказ
    defaultCallsPerDay: 80,
    defaultManagerSalary: 55000,
  },
  crmView: 'order',
  script: [
    { at: 600, say: { from: 'agent', text: 'Кафе-доставка «Вкусно Экспресс», Алексей. Что желаете заказать?' } },
    { at: 2400, say: { from: 'user', text: 'Пиццу пепперони и ролл Филадельфия.' } },
    { at: 3000, tool: { name: 'add_order_item', args: { name: 'Пицца Пепперони 40см', price: 790, qty: 1 } } },
    { at: 3500, tool: { name: 'add_order_item', args: { name: 'Ролл Филадельфия', price: 540, qty: 1 } } },
    { at: 4200, say: { from: 'agent', text: 'Добавил. Из напитков что-нибудь?' } },
    { at: 5400, say: { from: 'user', text: 'Колу 0.5.' } },
    { at: 5800, tool: { name: 'add_order_item', args: { name: 'Кола 0.5', price: 120, qty: 1 } } },
    { at: 6400, say: { from: 'agent', text: 'Куда доставить?' } },
    { at: 7600, say: { from: 'user', text: 'Улица Ленина 10, квартира 5.' } },
    { at: 8000, tool: { name: 'update_card', args: { field: 'address', value: 'ул. Ленина 10, кв. 5' } } },
    { at: 8500, say: { from: 'agent', text: 'Как вас зовут и номер телефона?' } },
    { at: 9800, say: { from: 'user', text: 'Дмитрий, 8 900 111 22 33.' } },
    { at: 10200, tool: { name: 'update_card', args: { field: 'name', value: 'Дмитрий' } } },
    { at: 10500, tool: { name: 'update_card', args: { field: 'phone', value: '8 900 111 22 33' } } },
    { at: 11000, say: { from: 'agent', text: 'Оплата наличными курьеру или картой онлайн?' } },
    { at: 12200, say: { from: 'user', text: 'Картой онлайн.' } },
    { at: 12500, tool: { name: 'update_card', args: { field: 'payment', value: 'Онлайн (безнал)' } } },
    { at: 13000, say: { from: 'agent', text: 'Секунду, считаю сумму…' } },
    { at: 14000, tool: { name: 'place_order', args: { deliveryTime: '~60 минут' } } },
    { at: 14500, say: { from: 'agent', text: 'Итого 1450 рублей, доставка бесплатно. Отправляю ссылку на оплату в SMS.' } },
    { at: 15000, tool: { name: 'show_sms', args: { text: 'Оплата заказа «Вкусно Экспресс» на 1450 ₽:', link: 'вкусно-экспресс.рф/pay/8842' } } },
    { at: 15800, tool: { name: 'lead_score', args: { score: 88, sentiment: 'позитивный' } } },
    { at: 16400, tool: { name: 'set_summary', args: { text: 'Дмитрий, ул. Ленина 10-5. Заказ: пицца Пепперони, ролл Филадельфия, кола — 1450 ₽, оплата онлайн. Отправлена ссылка на оплату.' } } },
    { at: 17000, say: { from: 'agent', text: 'Заказ принят, ждите курьера примерно через час. Приятного аппетита!' } },
  ],
};

const lendauto: NicheConfig = {
  id: 'lendauto',
  label: 'Прокат авто',
  emoji: '🚗',
  agentName: 'Марина, менеджер',
  fields: [
    { key: 'name', label: 'Имя' },
    { key: 'phone', label: 'Телефон' },
    { key: 'city', label: 'Город' },
    { key: 'car', label: 'Автомобиль' },
    { key: 'dateFrom', label: 'Дата от' },
    { key: 'dateTo', label: 'Дата до' },
  ],
  roi: {
    aiCostPerCall: 5,
    humanCostPerCall: 60,
    missedCallValue: 8000, // упущенная бронь
    defaultCallsPerDay: 30,
    defaultManagerSalary: 60000,
  },
  crmView: 'rental',
  script: [
    { at: 600, say: { from: 'agent', text: 'Lend Auto, добрый день, меня зовут Марина!' } },
    { at: 2400, say: { from: 'user', text: 'Здравствуйте, хочу арендовать машину на несколько дней.' } },
    { at: 3400, say: { from: 'agent', text: 'Отлично! Какой автомобиль вас интересует — эконом, комфорт или что-то побизнес-класса?' } },
    { at: 5200, say: { from: 'user', text: 'Что-нибудь комфортное, типа Kia Rio или Hyundai.' } },
    { at: 6000, say: { from: 'agent', text: 'Хорошо. Как вас зовут?' } },
    { at: 7200, say: { from: 'user', text: 'Александр.' } },
    { at: 7600, tool: { name: 'update_card', args: { field: 'name', value: 'Александр' } } },
    { at: 8200, say: { from: 'agent', text: 'Из какого вы города?' } },
    { at: 9400, say: { from: 'user', text: 'Краснодар.' } },
    { at: 9800, tool: { name: 'update_card', args: { field: 'city', value: 'Краснодар' } } },
    { at: 10400, tool: { name: 'update_card', args: { field: 'car', value: 'Kia Rio' } } },
    { at: 11000, say: { from: 'agent', text: 'На какие даты планируете аренду?' } },
    { at: 12600, say: { from: 'user', text: 'С 20 по 25 июня.' } },
    { at: 13200, tool: { name: 'update_card', args: { field: 'dateFrom', value: '20 июня' } } },
    { at: 13600, tool: { name: 'update_card', args: { field: 'dateTo', value: '25 июня' } } },
    { at: 14200, say: { from: 'agent', text: 'Секунду, проверяю наличие на эти даты…' } },
    { at: 15800, tool: { name: 'check_availability', args: { car: 'Kia Rio', dateFrom: '20 июня', dateTo: '25 июня' } } },
    { at: 16400, say: { from: 'agent', text: 'Kia Rio свободен! Пять суток — итого 16 000 рублей. Подскажите телефон для SMS?' } },
    { at: 18200, say: { from: 'user', text: '89221234567.' } },
    { at: 18600, tool: { name: 'update_card', args: { field: 'phone', value: '+7 922 123-45-67' } } },
    { at: 19400, say: { from: 'agent', text: 'Отправляю вам SMS со ссылкой для оформления брони.' } },
    { at: 20000, tool: { name: 'show_sms', args: { text: 'Lend Auto: Kia Rio, 20–25 июня, Краснодар. Оформите бронь:', link: 'https://go.lend-auto.ru/' } } },
    { at: 20400, tool: { name: 'book_car', args: { car: 'Kia Rio', dateFrom: '20 июня', dateTo: '25 июня', client: 'Александр', city: 'Краснодар' } } },
    { at: 20800, tool: { name: 'lead_score', args: { score: 88, sentiment: 'горячий' } } },
    { at: 21400, tool: { name: 'set_summary', args: { text: 'Александр, Краснодар — Kia Rio с 20 по 25 июня (5 сут, 16 000 ₽). Отправлено SMS со ссылкой на бронь.' } } },
    { at: 22000, say: { from: 'agent', text: 'Ссылка отправлена. Залог 10 000 рублей при получении авто. Ждём вас!' } },
  ],
};

const flowers: NicheConfig = {
  id: 'flowers',
  label: 'Магазин цветов',
  emoji: '💐',
  agentName: 'Алина, флорист',
  fields: [
    { key: 'name', label: 'Имя' },
    { key: 'phone', label: 'Телефон' },
    { key: 'address', label: 'Адрес доставки' },
    { key: 'occasion', label: 'Повод' },
  ],
  roi: {
    aiCostPerCall: 4,
    humanCostPerCall: 45,
    missedCallValue: 3000, // упущенный заказ букета
    defaultCallsPerDay: 40,
    defaultManagerSalary: 50000,
  },
  crmView: 'order',
  script: [
    { at: 600, say: { from: 'agent', text: 'Цветочная мастерская «Флёр», флорист Алина. Здравствуйте! Что хотите подобрать?' } },
    { at: 2600, say: { from: 'user', text: 'Нужен букет на день рождения, что-нибудь яркое.' } },
    { at: 3200, tool: { name: 'update_card', args: { field: 'occasion', value: 'День рождения' } } },
    { at: 4000, say: { from: 'agent', text: 'Отлично! Есть пионовый букет за 4500 ₽ или 25 роз за 3250 ₽. Что ближе?' } },
    { at: 5800, say: { from: 'user', text: 'Давайте 25 красных роз.' } },
    { at: 6400, tool: { name: 'add_order_item', args: { name: 'Розы красные 60 см', price: 130, qty: 25, unit: 'шт' } } },
    { at: 6900, tool: { name: 'add_order_item', args: { name: 'Оформление букета', price: 500, qty: 1, unit: 'шт' } } },
    { at: 7200, say: { from: 'agent', text: '25 роз — 3250 ₽ плюс оформление 500 ₽, итого 3750 ₽, доставка бесплатно. Куда доставить?' } },
    { at: 8600, say: { from: 'user', text: 'Улица Пушкина 12, квартира 5.' } },
    { at: 9000, tool: { name: 'update_card', args: { field: 'address', value: 'ул. Пушкина 12, кв. 5' } } },
    { at: 9800, say: { from: 'agent', text: 'На какое время доставка, и как вас зовут с телефоном?' } },
    { at: 11200, say: { from: 'user', text: 'Сегодня к 17:00. Олег, 89031234567.' } },
    { at: 11700, tool: { name: 'update_card', args: { field: 'name', value: 'Олег' } } },
    { at: 12100, tool: { name: 'update_card', args: { field: 'phone', value: '+7 903 123-45-67' } } },
    { at: 12800, say: { from: 'agent', text: 'Секунду, оформляю заказ…' } },
    { at: 13600, tool: { name: 'place_order', args: { deliveryTime: 'сегодня к 17:00' } } },
    { at: 14200, say: { from: 'agent', text: 'Готово! Букет из 25 роз с оформлением — 3750 ₽, доставка бесплатно. Отправляю подтверждение в SMS.' } },
    { at: 14800, tool: { name: 'show_sms', args: { text: 'Заказ «Флёр»: букет из 25 роз, 3750 ₽, доставка сегодня к 17:00:', link: 'fleur.ru/order/2231' } } },
    { at: 15600, tool: { name: 'lead_score', args: { score: 86, sentiment: 'позитивный' } } },
    { at: 16400, tool: { name: 'set_summary', args: { text: 'Олег — букет из 25 красных роз + оформление (3750 ₽) на день рождения, доставка сегодня к 17:00, ул. Пушкина 12-5. Отправлено SMS.' } } },
    { at: 17200, say: { from: 'agent', text: 'Заказ принят! Доставим сегодня к 17:00. Спасибо, что выбрали «Флёр»!' } },
  ],
};

export const NICHES: Record<string, NicheConfig> = { dental, auto, meat, salon, food, lendauto, flowers };
// Прокат авто — первый (демо для клиента), салон — дефолт для живого Dasha.
export const NICHE_LIST: NicheConfig[] = [lendauto, salon, food, flowers, dental, auto, meat];
export const DEFAULT_NICHE: NicheConfig = lendauto;
